- name: Master Copy my.cnf master MySQL configuration.
  template:
    src: my.cnf.master.j2
    dest: "{{ mysql_config_file }}"
    owner: root
    group: root
    mode: 0644
  tags: master

- name: Master Verify mysql include directory exists.
  file:
    path: "{{ mysql_config_include_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags: master

#- name: disable firewalld
#  shell: systemctl disable firewalld
#  args:
#    warn: False
#  ignore_errors: true
#  tags: master
#
#- name: stop firewalld
#  shell: systemctl stop firewalld

- name: Master Systemctl Start mysqld
  shell: systemctl restart mysqld.service
  tags: master

- name: Master Systemctl enable mysqld
  shell: systemctl enable mysqld.service
  tags: master
